name: "P6 GHA: Upgrade Dependencies for a CDK Construct"
description: "Upgrades dependencies for a CDK Construct and opens a PR"
author: "Philip M. Gollucci"

inputs:
  gh_token:
    description: "GitHub Token (Classic PAT with repo scope)"
    required: true

runs:
  using: "composite"
  steps:
    # -------------------------
    # Checkout the repository
    # -------------------------
    - name: Checkout main branch
      uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 0
        ref: main
        persist-credentials: false  # we'll configure auth manually

    # -------------------------
    # Setup Node environment
    # -------------------------
    - name: Setup Node
      uses: p6m7g8-actions/node-yarn-setup@main

    # -------------------------
    # Upgrade project dependencies
    # -------------------------
    - name: Upgrade Dependencies
      shell: bash
      run: |
        yarn up '*'

    - name: Check for changes
      shell: bash
      run: |
        git diff > diff.txt
        echo "diff<<EOF" >> "$GITHUB_ENV"
        cat diff.txt >> "$GITHUB_ENV"
        echo "EOF" >> "$GITHUB_ENV"
        rm -f diff.txt

    # -------------------------
    # Create or update the PR
    # -------------------------
    - name: Create Pull Request
      id: create_pr
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ -z "$diff" ]; then
          echo "No changes to commit"
          exit 0
        fi

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git checkout -b github-actions/upgrade-main
        git add .
        git commit -m "chore(deps): upgrade dependencies"

        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git push --set-upstream origin github-actions/upgrade-main

        pr_url=$(gh pr create --title "chore(deps): upgrade dependencies" --body "This PR upgrades project dependencies." --head github-actions/upgrade-main --base main || gh pr view --json url --jq .url)
        echo "pr_url=$pr_url" >> "$GITHUB_OUTPUT"
