name: "Upgrade Dependencies Action"
description: "Composite action to upgrade dependencies, create a diff, and open a pull request"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Install Node.js
      shell: bash
      run: |
        curl -fsSL https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-x64.tar.xz -o node-v22.11.0-linux-x64.tar.xz
        sudo tar -xJf node-v22.11.0-linux-x64.tar.xz -C /usr/local
        echo "/usr/local/node-v22.11.0-linux-x64/bin" >> $GITHUB_PATH
    - name: Restore NPM node_modules cache
      uses: actions/cache/restore@v4.1.2
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-node_modules-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-node_modules-
    - name: Corepack
      shell: bash
      run: |
        set +e
        sudo corepack enable
        sudo corepack prepare yarn@latest --activate
    - name: Check Node
      shell: bash
      run: |
        set +e
        ls -alFh /usr/local/node-v22.11.0-linux-x64/bin
        which node
        which npm
        which yarn
        which corepack
        node -v
        npm -v
        yarn --version
        corepack --version
        echo $PATH
    # - name: Install node_modules
    #   shell: bash
    #   run: |
    #     yarn install
    #     yarn explain peer-requirements
    - name: Cache NPM dependencies
      uses: actions/cache@v4.1.2
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-node_modules-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-node_modules-
    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v7.0.5
      with:
        token: ${{ secrets.P6_PGOLLUCCI_GH_TOKEN }}
        commit-message: |
          chore(deps): upgrade dependencies
        branch: github-actions/upgrade-main
        title: "chore(deps): upgrade dependencies"
        labels: auto-merge
        body: |
          Upgrades project dependencies. The following changes were made:
          ```diff
          ${{ env.diff }}
          ```
        author: github-actions <github-actions@github.com>
        committer: github-actions <github-actions@github.com>
        signoff: true