name: "P6 GHA: Upgrade Dependencies for a CDK Construct"
description: "P6 GHA: Upgrade Dependencies for a CDK Construct"
author: "Philip M. Gollucci"
inputs:
  gh_token:
    description: "GitHub Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v5.0.0
      with:
        fetch-depth: 0
        ref: main
    - name: Setup Node
      uses: p6m7g8-actions/node-yarn-setup@main
    - name: Upgrade Dependencies
      shell: bash
      run: yarn up '*'
    - name: Export token for create-pull-request
      shell: bash
      run: echo "GITHUB_TOKEN=${{ inputs.gh_token }}" >> $GITHUB_ENV
    - name: Prime git auth for PR
      shell: bash
      run: |
        auth="$(printf "x-access-token:${{ inputs.gh_token }}" | base64 | tr -d '\n')"
        git config --local http.https://github.com/.extraheader "AUTHORIZATION: basic ${auth}"
    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v7.0.8
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
      with:
        token: ${{ inputs.gh_token }}
        branch-token: ${{ inputs.gh_token }}
        commit-message: |
          chore(deps): upgrade dependencies
        branch: github-actions/upgrade-main
        title: "chore(deps): upgrade dependencies"
        labels: auto-merge
        body: |
          Upgrades project dependencies. The following changes were made:
          ```diff
          ${{ env.diff }}
          ```
        author: github-actions <github-actions@github.com>
        committer: github-actions <github-actions@github.com>
        signoff: true
